version: 2.1

parameters:
  build_core:
    type: boolean
    default: false
  build_mock:
    type: boolean
    default: false
  build_sql:
    type: boolean
    default: false
  build_redis:
    type: boolean
    default: false
  build_bull:
    type: boolean
    default: false
  build_pg_kysely:
    type: boolean
    default: false
  build_pg_knex:
    type: boolean
    default: false
  build_pg_sequelize:
    type: boolean
    default: false
  build_pglite_driver:
    type: boolean
    default: false
  build_s3:
    type: boolean
    default: false

orbs:
  vn-ci: versatile/vn-ci@1

workflows:
  core:
    when: <<pipeline.parameters.build_core>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/core"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  mock:
    when: <<pipeline.parameters.build_mock>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/mock"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  sql:
    when: <<pipeline.parameters.build_sql>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/sql"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  redis:
    when: <<pipeline.parameters.build_redis>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/redis"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  bull:
    when: <<pipeline.parameters.build_bull>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/bull"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  pg-kysely:
    when: <<pipeline.parameters.build_pg_kysely>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/pg-kysely"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  pg-knex:
    when: <<pipeline.parameters.build_pg_knex>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/pg-knex"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  pg-sequelize:
    when: <<pipeline.parameters.build_pg_sequelize>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/pg-sequelize"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  pglite-driver:
    when: <<pipeline.parameters.build_pglite_driver>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/pglite-driver"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
  s3:
    when: <<pipeline.parameters.build_s3>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/s3"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
          filters:
            branches:
              only: main
