version: 2.1

parameters:
  build_core:
    type: boolean
    default: false
  build_redis:
    type: boolean
    default: false
  build_pg_kysely:
    type: boolean
    default: false
  build_pg_knex:
    type: boolean
    default: false
  build_pg_sequelize:
    type: boolean
    default: false
  build_s3:
    type: boolean
    default: false

orbs:
  vn-ci: versatile/vn-ci@0.0.32

workflows:
  core:
    when: <<pipeline.parameters.build_core>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/core"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
  redis:
    when: <<pipeline.parameters.build_redis>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/redis"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
  pg-kysely:
    when: <<pipeline.parameters.build_pg_kysely>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/pg-kysely"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
  pg-knex:
    when: <<pipeline.parameters.build_pg_knex>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/pg-knex"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
  pg-sequelize:
    when: <<pipeline.parameters.build_pg_sequelize>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/pg-sequelize"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
  s3:
    when: <<pipeline.parameters.build_s3>>
    jobs:
      - vn-ci/init:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          package_json_dir: "packages/s3"
      - vn-ci/build-publish:
          context: base-context
          is_default_branch: <<pipeline.git.branch.is_default>>
          requires:
            - vn-ci/init
