version: 2.1
orbs:
  node: circleci/node@7.2.1

jobs:
  ci:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - node/install:
          node-version: "22"
      - run:
          name: "Run CI workflow"
          command: ./.circleci/ci.sh

workflows:
  test-build-publish:
    jobs:
      - ci:
          context:
            - base-context
          filters:
            branches:
              ignore:
                - dependabot/**
